# Generated by Django 3.2.16 on 2022-12-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('cognome', models.CharField(blank=True, max_length=50)),
                ('data_di_nascita', models.DateField()),
            ],
        ),
    ]
