# Generated by Django 3.2.16 on 2022-12-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Persone'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='cognome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
