# Generated by Django 3.2.16 on 2022-12-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0002_auto_20221212_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='indirizzo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
