# Generated by Django 3.2.16 on 2022-12-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0003_persona_indirizzo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='indirizzo',
            field=models.CharField(blank=True, help_text="inserisci qui l'indirizzo dove abita la persona", max_length=50, verbose_name='indirizzo di residenza'),
        ),
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('nome', 'cognome')},
        ),
    ]
