# Generated by Django 3.2.16 on 2022-12-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0004_auto_20221212_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='data_di_nascita',
            field=models.DateField(blank=True),
        ),
    ]
