# Generated by Django 3.2.16 on 2022-12-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0005_alter_persona_data_di_nascita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='data_di_nascita',
            field=models.DateField(),
        ),
    ]
