# Generated by Django 3.2.16 on 2022-12-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0007_studente'),
    ]

    operations = [
        migrations.AddField(
            model_name='studente',
            name='voto',
            field=models.PositiveSmallIntegerField(default=6),
            preserve_default=False,
        ),
    ]
