# Generated by Django 3.2.16 on 2022-12-12 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0008_studente_voto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_compito', models.CharField(max_length=15)),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagrafica.studente')),
            ],
        ),
    ]
