# Generated by Django 3.2.16 on 2022-12-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0009_compito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compito',
            options={'verbose_name': 'Compito', 'verbose_name_plural': 'Compiti'},
        ),
        migrations.AlterModelOptions(
            name='studente',
            options={'verbose_name': 'Studente', 'verbose_name_plural': 'Studenti'},
        ),
        migrations.AddField(
            model_name='compito',
            name='voto',
            field=models.PositiveSmallIntegerField(default=6),
            preserve_default=False,
        ),
    ]
