# Generated by Django 3.2.16 on 2022-12-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0010_auto_20221212_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_materia', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materie',
            },
        ),
        migrations.AlterField(
            model_name='studente',
            name='voto',
            field=models.PositiveSmallIntegerField(verbose_name='voto medio'),
        ),
    ]
