# Generated by Django 3.2.16 on 2022-12-12 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0011_auto_20221212_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compito',
            name='tipo_compito',
            field=models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, to='anagrafica.materia'),
        ),
    ]
