# Generated by Django 3.2.16 on 2022-12-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0012_alter_compito_tipo_compito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studente',
            name='voto',
            field=models.SmallIntegerField(default=0, verbose_name='voto medio'),
        ),
    ]
