# Generated by Django 3.2.16 on 2022-12-14 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagrafica', '0014_auto_20221213_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genitore',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='anagrafica.persona')),
                ('figlio', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='anagrafica.studente')),
            ],
            bases=('anagrafica.persona',),
        ),
    ]
